pre_composer_script: |
    #!/bin/bash
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/secret:.*/secret: fec3dc7bfd20cc8c2bd10148631513ec89/" app/config/parameters.yml

post_composer_script: |
    #!/bin/bash
    #echo "    doctrine.server_version: 5.6" >> app/config/parameters.yml
    #./app/console cache:warmup --no-interaction
    ./app/console doctrine:database:create --no-interaction
    ./app/console doctrine:schema:update --force --no-interaction
    #./app/console doctrine:migrations:status --no-interaction
    #./app/console doctrine:migrations:migrate --no-interaction
    ./app/console assets:install web --symlink --no-interaction
    ./app/console assetic:dump --no-interaction
    #./app/console doctrine:fixtures:load --no-interaction
